### ISSUE TITLE
JSX tree handled incorrectly

### ISSUE THREAD

**Issue by vdanchenkov** [colingourlay/hyperstyles#3]
In JSX following tree
    
    <a>
      <b/>
      <c/>
    </a>

is equivalent to following code

    h('a', null,
        h('b', null),
        h('c', null)
    ) 

Note that children are not wrapped in an array. 

Current implementation breaks on null arguments. And if we replace nulls with {} it will ignore all children after b element. Test code:

	t.equal(
		h('a', null,
			h('b', null),
			h('c', null)
		).props.children.length,
		2
	);

**Comment by colingourlay** [comment]
I'm aware of the issue of ignored children, as the original transform counted on all the children being in a single argument (an array). I already planned to just pass-through all arguments as they are to solve this issue (which would have been a problem for `crel` and `hyperscript` too).

Thanks for raising the issue of the null arguments that are generated from the JSX transform. I forgot React cared about positional arguments (rather than the optional arguments that `virtual-hyperscript` deals with.

I should really simplify the transform function to make a lot less assumptions, as it only really needs to care about the tagName (with potential className shorthand content) and the properties object (which it may need to create in the case of a `null` argument).

**Comment by vdanchenkov** [comment]
Speaking of simplification. I thought of a more simple implementation but it will lack some functionality. 

Transform function separately handles first and second arguments and pass through everything else.
#### First argument:
If first argument is a string - look for classes and replace them in place. I.e. `div.test#id` becomes `div.test_5hfdjhjf#id`

#### Second argument:
If it's an object that have property styleName, split object.styleName by space, map with css module and append to className.

Drawback of described approach is that h('div.class') will not work out of the box with 

    var h = hyperstyles(React.createElement, styles);

But it will work if used as a simple wrapper for react-hyperscript or virtual-hyperscript

    var h = hyperstyles(require('react-hyperscript'), styles);
